### ISSUE TITLE
Polling errors reported 

### ISSUE THREAD

**Issue by apisto64** [Luligu/homebridge-somfy-tahoma-screen#1]
**Describe The Bug:**
I have some problems when asking to command all shutters ; in some cases, some of them are not electrically commanded

**To Reproduce:**
It appears  when I ask to command all shutters in a same command

**Expected behavior:**
All shutter must be properly commanded (that was working in the past)

**Logs:**
see attached file

**Plugin Config:**

```json
see attached file


**Screenshots:**
None

**Environment:**

* **Plugin Version**: 
* **Homebridge Version**: 1.7.0
* **Node.js Version**: 20.9.0
* **NPM Version**:  10.1.0
* **Operating System**: Raspbian GNU/Linux Bullseye (11)
*
<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->
[Errors log.txt](https://github.com/Luligu/homebridge-somfy-tahoma-screen/files/14542009/Errors.log.txt)
[Json config.txt](https://github.com/Luligu/homebridge-somfy-tahoma-screen/files/14542025/Json.config.txt)

**Comment by Luligu** [comment]
Hi I'm not sure I understand correctly. 
Can you post the full log please?
In your issue I found no attachements.
