### ISSUE TITLE
Awning is not showing up in HomeKit

### ISSUE THREAD

**Issue by steffmatoc24** [Luligu/homebridge-somfy-tahoma-screen#10]
Hi, 

first thank you very much for the work on this plugin!!! 

I noticed that my shutter got recognized but the Awning is not showing up in HomeKit. 
Is there a wa for mer to fix it?

Device: Markise 
[14:34:09.972] [Somfy TaHoma Screen] - uniqueName Awning 
[14:34:09.972] [Somfy TaHoma Screen] - uiClass Awning 
[14:34:09.972] [Somfy TaHoma Screen] - serial 
[14:34:09.972] [Somfy TaHoma Screen] - deviceURL ogp://
[14:34:09.972] [Somfy TaHoma Screen] - commands: ["deploy","goToAlias","identify","rollOut","rollUp","saveAlias","setName","stop","undeploy"] 
[14:34:09.972] [Somfy TaHoma Screen] - states: [{"name":"core:AvailabilityState","type":3,"value":"available"},{"name":"core:StatusState","type":3,"value":"available"}]

**Comment by Luligu** [comment]
Hi, 
so to add the device is easy.

More complicated is that "deploy","goToAlias","identify","rollOut","rollUp","saveAlias","setName","stop","undeploy" are not the standard commands.

I need time but I will do it.

Thanks for your interest.

**Comment by steffmatoc24** [comment]
Hi, 

thank you for your reply, time and service!!

**Comment by mopac01** [comment]
Thank you @Luligu for your work here.   I too ave an awning with a Somfy motor and the Tahoma hub.   I'd be very grateful if you updating your plugin to work with awnings.

**Comment by Luligu** [comment]
Hi,
I published the new release.
## [1.1.0] - 2024-10-11

### Added

- [homebridge]: Added support for homebridge v2 (https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0).
- [somfy]: Added support for uniqueName = RollerShutterRTSComponent.
- [somfy]: Added support for uniqueName = HorizontalAwningRTSComponent.
- [somfy]: Added support for uniqueName = PergolaHorizontalUnoIOComponent.
- [somfy]: Added support for uniqueName = Awning.


<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

I have no way to test it against your screen.

Can you try and let me know please?

My Best.

**Comment by Jeffo31350** [comment]
Hi,
Thanks for the new release.  My awning has appeared this morning and is working, however is there a way to reverse the direction of movement.  It reports "Open" when it's  closed and "Closed" when it is open.
Many thanks.
--Phil

**Comment by Luligu** [comment]
Yeah I had that idea that I mapped wrongly close and rollUp...
Will fix thanks for testing.

**Comment by Luligu** [comment]
Fixed 
## [1.1.2] - 2024-10-12

### Fixed

- [somfy]: Fixed the commands "rollOut", "rollUp" for Awning.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>

**Comment by steffmatoc24** [comment]
I have the same issue with the shutter type! Thank you for fixing it for awning so quickly!

**Comment by Luligu** [comment]
Thanks for your appreciation...
This release should include all without having to hard code each screen uiClass.
I'm just wandering if this will create same issues with specific devices...
Let's see...
