### ISSUE TITLE
Please add support for Exterior Venetian Blinds

### ISSUE THREAD

**Issue by cbrandlehner** [Luligu/homebridge-somfy-tahoma-screen#6]
**Is your feature request related to a problem? Please describe:**
Enhancement request to support another device type.

```
[10:20:17.214] [Somfy TaHoma Screen] Device: Unten-2 
[10:20:17.214] [Somfy TaHoma Screen] - uniqueName ExteriorVenetianBlindRTSComponent 
[10:20:17.215] [Somfy TaHoma Screen] - uiClass ExteriorVenetianBlind 
[10:20:17.215] [Somfy TaHoma Screen] - serial 4ae9ec4a-d662-4618-baa4-17c6e1406470 
[10:20:17.216] [Somfy TaHoma Screen] - deviceURL rts://2078-1423-4018/16746565 
[10:20:17.216] [Somfy TaHoma Screen] - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[10:20:17.216] [Somfy TaHoma Screen] - states: [] 
[10:20:17.241] [Somfy TaHoma Screen] Device: Unten-4 
[10:20:17.242] [Somfy TaHoma Screen] - uniqueName ExteriorVenetianBlindRTSComponent 
[10:20:17.243] [Somfy TaHoma Screen] - uiClass ExteriorVenetianBlind 
[10:20:17.243] [Somfy TaHoma Screen] - serial 9d4b13e8-51b9-4914-b1d5-047593aca644 
[10:20:17.244] [Somfy TaHoma Screen] - deviceURL rts://2078-1423-4018/16769535 
[10:20:17.245] [Somfy TaHoma Screen] - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[10:20:17.245] [Somfy TaHoma Screen] - states: [] 
[10:20:17.263] [Somfy TaHoma Screen] TaHoma 0 screens discovered 
```

**Comment by Luligu** [comment]
Hi,
I added but since I cannot test, could you please send me a full log from when you load hb and also when you control the devices?


## [1.0.19] - 2024-07-22

### Changed

- [somfy]: Added support ExteriorVenetianBlindRTSComponent.
- [homebridge]: Update Homebridge to v.1.8.4.
- [dependencies]: Update dependencies and devDependencies.

**Comment by cbrandlehner** [comment]
Thanks, busy during week, will try to test on weekend.

**Comment by cbrandlehner** [comment]
@Luligu that new version works perfectly for me. Finally I can control my Somfy RTS Blinds with Apple Home as the Somfy Homekit Bridge for whatever reason only supports some Somy products.
![IMG_2085](https://github.com/user-attachments/assets/c9858d47-e684-4be3-a7e8-f73ac1953073)

**Comment by cbrandlehner** [comment]
This is the log:

`[7/27/2024, 7:52:55 AM] Homebridge v1.8.4 (HAP v0.12.2) (Somfy TaHoma Screen) is running on port 32746.
[7/27/2024, 7:52:55 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[38;5;245m[07:52:56.235] [38;5;31m[Somfy TaHoma Screen][38;5;245m POST /login 
[38;5;245m[07:52:56.505] [38;5;31m[Somfy TaHoma Screen][38;5;252m TaHoma service connected 
[38;5;245m[07:52:56.506] [38;5;31m[Somfy TaHoma Screen][38;5;245m Enable event polling period every 60 sec 
[38;5;245m[07:52:56.507] [38;5;31m[Somfy TaHoma Screen][38;5;245m POST /events/register 
[38;5;245m[07:52:56.509] [38;5;31m[Somfy TaHoma Screen][38;5;245m GET /setup/devices 
[38;5;245m[07:52:56.696] [38;5;31m[Somfy TaHoma Screen][38;5;252m TaHoma 19 devices discovered 
[38;5;245m[07:52:56.697] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: HOMEKIT (stack) 
[38;5;245m[07:52:56.697] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName StackComponent 
[38;5;245m[07:52:56.697] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 7d5b3668-429f-4ea8-8743-1e34fdaf14ce 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL homekit://2078-1423-4018/stack 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["deleteControllers"] 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Box 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName PodV3Component 
[38;5;245m[07:52:56.698] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass Pod 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial b6de9012-626c-40ae-9eed-ded84af34a9a 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL internal://2078-1423-4018/pod/0 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["getName","update","setCountryCode","activateCalendar","deactivateCalendar","refreshPodMode","refreshUpdateStatus","setCalendar","setLightingLedPodMode","setPodLedOff","setPodLedOn"] 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"internal:LightingLedPodModeState","type":2,"value":1},{"name":"core:CountryCodeState","type":3,"value":"AT"},{"name":"internal:Button1State","type":3,"value":"pressed"},{"name":"internal:Button3State","type":3,"value":"pressed"},{"name":"core:LocalAccessProofState","type":3,"value":"localAccessProof"},{"name":"core:LocalIPv4AddressState","type":3,"value":"192.168.71.74"},{"name":"core:NameState","type":3,"value":"Box"}] 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: INTERNAL (wifi/0) 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName WifiComponent 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass Wifi 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 7ecb0794-4724-44ee-9828-fe790e7dc483 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL internal://2078-1423-4018/wifi/0 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["clearCredentials","setTargetInfraConfig","setWifiMode"] 
[38;5;245m[07:52:56.699] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"internal:WifiModeState","type":3,"value":"infrastructure"},{"name":"internal:CurrentInfraConfigState","type":3,"value":"C2Home"},{"name":"internal:SignalStrengthState","type":1,"value":54}] 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Rollo-rechts 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName RollerShutterGenericIOComponent 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass RollerShutter 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 20ff88d7-f254-464e-b752-ebacb7a9c0e8 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL io://2078-1423-4018/542500 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["addLockLevel","advancedRefresh","close","delayedStopIdentify","down","getName","identify","my","open","refreshMemorized1Position","removeLockLevel","resetLockLevels","setClosure","setDeployment","setMemorized1Position","setName","setPosition","setSecuredPosition","startIdentify","stop","stopIdentify","up","wink","runManufacturerSettingsCommand","keepOneWayControllersAndDeleteNode","pairOneWayController","sendIOKey","setConfigState","unpairAllOneWayControllersAndDeleteNode","unpairAllOneWayControllers","unpairOneWayController"] 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"core:NameState","type":3,"value":"Rollo-rechts"},{"name":"core:PriorityLockTimerState","type":1,"value":0},{"name":"core:CommandLockLevelsState","type":3,"value":"[]","lastUpdateTime":1721330623000},{"name":"core:StatusState","type":3,"value":"available"},{"name":"core:DiscreteRSSILevelState","type":3,"value":"normal"},{"name":"core:RSSILevelState","type":2,"value":62},{"name":"core:ClosureState","type":1,"value":31},{"name":"core:TargetClosureState","type":1,"value":31},{"name":"core:OpenClosedState","type":3,"value":"open"},{"name":"core:MovingState","type":6,"value":false},{"name":"core:Memorized1PositionState","type":1,"value":81}] 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: IO (5470863) 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName StackComponent 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.700] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial abd59f85-09e7-4832-bfe2-8475c15e64d1 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL io://2078-1423-4018/5470863 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["advancedSomfyDiscover","discover1WayController","discoverActuators","discoverSensors","discoverSomfyUnsetActuators","joinNetwork","resetNetworkSecurity","shareNetwork"] 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Rollo links 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName RollerShutterGenericIOComponent 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass RollerShutter 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 8c6051e2-a923-4ab6-b15b-c49b5fa21286 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL io://2078-1423-4018/8599050 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["addLockLevel","advancedRefresh","close","delayedStopIdentify","down","getName","identify","my","open","refreshMemorized1Position","removeLockLevel","resetLockLevels","setClosure","setDeployment","setMemorized1Position","setName","setPosition","setSecuredPosition","startIdentify","stop","stopIdentify","up","wink","runManufacturerSettingsCommand","keepOneWayControllersAndDeleteNode","pairOneWayController","sendIOKey","setConfigState","unpairAllOneWayControllersAndDeleteNode","unpairAllOneWayControllers","unpairOneWayController"] 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"core:NameState","type":3,"value":"Rollo links"},{"name":"core:PriorityLockTimerState","type":1,"value":0},{"name":"core:CommandLockLevelsState","type":3,"value":"[]","lastUpdateTime":1721330623000},{"name":"core:StatusState","type":3,"value":"available"},{"name":"core:DiscreteRSSILevelState","type":3,"value":"normal"},{"name":"core:RSSILevelState","type":2,"value":58},{"name":"core:ClosureState","type":1,"value":31},{"name":"core:Memorized1PositionState","type":1,"value":80},{"name":"core:MovingState","type":6,"value":false},{"name":"core:TargetClosureState","type":1,"value":31},{"name":"core:OpenClosedState","type":3,"value":"open"}] 
[38;5;245m[07:52:56.701] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: OGP KNX Bridge 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName Bridge 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 77671fa0-493d-46aa-b1e9-75d1e2a42339 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL ogp://2078-1423-4018/00000BE8 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["identify","reset","sendPrivate","setName"] 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"core:NameState","type":3,"value":"OGP KNX Bridge"}] 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: OGP Sonos Bridge 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName Bridge 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 93c93b8e-ab37-431f-9ef9-e41d4fe2fc76 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL ogp://2078-1423-4018/0003FEF3 
[38;5;245m[07:52:56.702] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["discover","reset"] 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"core:NameState","type":3,"value":"OGP Sonos Bridge"}] 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: OGP Siegenia Bridge 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName Bridge 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 06bd8ed0-a1c5-4d84-8510-542d12d513d3 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL ogp://2078-1423-4018/039575E9 
[38;5;245m[07:52:56.703] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["discover","identify","setName"] 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"core:NameState","type":3,"value":"OGP Siegenia Bridge"}] 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: OGP Intesis Bridge 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName Bridge 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 30af380b-2e23-4fb0-a826-d4ff58cd66af 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL ogp://2078-1423-4018/09E45393 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["discover","identify","setName"] 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [{"name":"core:NameState","type":3,"value":"OGP Intesis Bridge"}] 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Oben-3 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.704] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 87ffb3de-304f-4872-8916-d4d061f679f8 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16723826 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Unten-3 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial f54a8d57-90a2-4f09-a0b6-5a2c5f2f42d2 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16725105 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.705] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Oben-1 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 03c3712e-8028-4a61-b43d-bf81cf7e652a 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16725410 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Oben-4 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial dbfa0d2f-6a47-4665-8cd8-8dbe2c26b174 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16726980 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.706] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Unten-1 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 74c31af1-cb79-4c40-ae95-3b1cee37003e 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16732957 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Oben-2 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 74a08a16-3b56-4197-ad50-18aaf4adc230 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16737941 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.707] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Unten-2 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 4ae9ec4a-d662-4618-baa4-17c6e1406470 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16746565 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: Unten-4 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName ExteriorVenetianBlindRTSComponent 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ExteriorVenetianBlind 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial 9d4b13e8-51b9-4914-b1d5-047593aca644 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL rts://2078-1423-4018/16769535 
[38;5;245m[07:52:56.708] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: ["close","down","identify","my","open","rest","stop","test","up","moveOf","openConfiguration","tiltNegative","tiltPositive"] 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m Device: ZIGBEE (65535) 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uniqueName TransceiverV3_0Component 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - uiClass ProtocolGateway 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - serial fb86c10e-e2e4-448e-a76d-ce2a235c5f88 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - deviceURL zigbee://2078-1423-4018/65535 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - commands: [] 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;245m - states: [] 
[38;5;245m[07:52:56.709] [38;5;31m[Somfy TaHoma Screen][38;5;252m TaHoma 8 screens discovered 
[38;5;245m[07:52:56.710] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Oben-3 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial 87ffb3de-304f-4872-8916-d4d061f679f8 
[38;5;245m[07:52:56.713] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Oben-3 
[38;5;245m[07:52:56.727] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Unten-3 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial f54a8d57-90a2-4f09-a0b6-5a2c5f2f42d2 
[38;5;245m[07:52:56.727] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Unten-3 
[38;5;245m[07:52:56.734] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Oben-1 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial 03c3712e-8028-4a61-b43d-bf81cf7e652a 
[38;5;245m[07:52:56.734] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Oben-1 
[38;5;245m[07:52:56.741] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Oben-4 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial dbfa0d2f-6a47-4665-8cd8-8dbe2c26b174 
[38;5;245m[07:52:56.741] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Oben-4 
[38;5;245m[07:52:56.748] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Unten-1 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial 74c31af1-cb79-4c40-ae95-3b1cee37003e 
[38;5;245m[07:52:56.748] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Unten-1 
[38;5;245m[07:52:56.751] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Oben-2 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial 74a08a16-3b56-4197-ad50-18aaf4adc230 
[38;5;245m[07:52:56.752] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Oben-2 
[38;5;245m[07:52:56.756] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Unten-2 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial 4ae9ec4a-d662-4618-baa4-17c6e1406470 
[38;5;245m[07:52:56.756] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Unten-2 
[38;5;245m[07:52:56.766] [38;5;31m[Somfy TaHoma Screen][38;5;245m Adding device: Unten-4 uniqueName ExteriorVenetianBlindRTSComponent uiClass ExteriorVenetianBlind serial 9d4b13e8-51b9-4914-b1d5-047593aca644 
[38;5;245m[07:52:56.766] [38;5;31m[Somfy TaHoma Screen][38;5;252m Restoring existing accessory: Unten-4 
[7/27/2024, 7:53:29 AM] [Door-Terrasse-links] Received MQTT: c2home/zigbee2mqtt/Door-Terrasse-links/state = Closed
[38;5;245m[07:53:32.103] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-3 100 
[38;5;245m[07:53:32.105] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-2 100 
[38;5;245m[07:53:32.109] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-4 100 
[38;5;245m[07:53:32.110] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-1 100 
[38;5;245m[07:53:56.512] [38;5;31m[Somfy TaHoma Screen][38;5;245m POST /events/f2bfd4cb-0a19-0483-48ab-63959bd0842a/fetch 
[38;5;245m[07:54:26.778] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-3 100 
[38;5;245m[07:54:26.779] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-2 100 
[38;5;245m[07:54:26.779] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-4 100 
[38;5;245m[07:54:26.780] [38;5;31m[Somfy TaHoma Screen][38;5;245m onGetCurrentPosition Unten-1 100 
[38;5;245m[07:54:28.566] [38;5;31m[Somfy TaHoma Screen][38;5;245m onSetTargetPosition Unten-2 0 
Closing current 100 target 0 duration 26 steps 100`

**Comment by Luligu** [comment]
Hi,
thanks for the feedback.

Somfy bridge only supports bidirectional radio...
